name: Build Windows pybind11 extensions

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: List root directory files (debug)
        run: dir

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pybind11
          pip install -r requirements.txt

      - name: Clone vcpkg
        run: git clone https://github.com/microsoft/vcpkg.git

      - name: Bootstrap vcpkg
        run: .\vcpkg\bootstrap-vcpkg.bat

      - name: Install OpenCV via vcpkg
        run: .\vcpkg\vcpkg install opencv

      - name: Configure and build with CMake
        run: |
          mkdir build
          cd build
          cmake ${{ github.workspace }} -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake
          cmake --build . --config Release

      - name: Upload built extensions
        uses: actions/upload-artifact@v4
        with:
          name: windows-pyd-modules
          path: |
            build/Release/image_utils.pyd
            build/Release/thumbnail_utils.pyd
