name: CMake Configure Test

on:
  push:
    paths:
      - 'src/image_sorter/cpp/**'
      - '.github/workflows/cmake-configure-test.yml'

jobs:
  cmake-configure-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Print working directory
        shell: pwsh
        run: pwd

      - name: Clone vcpkg fresh
        run: git clone --depth=1 https://github.com/microsoft/vcpkg.git vcpkg
        shell: pwsh

      - name: List vcpkg contents
        shell: pwsh
        run: |
          Write-Host "Listing vcpkg dir:"
          Get-ChildItem -Force "${{ github.workspace }}\vcpkg"
          Write-Host "Listing scripts/buildsystems dir:"
          Get-ChildItem -Force "${{ github.workspace }}\vcpkg\scripts\buildsystems"

      - name: Bootstrap vcpkg
        shell: pwsh
        run: .\vcpkg\bootstrap-vcpkg.bat

      - name: Check toolchain path exists
        shell: pwsh
        run: |
          $toolchain = "${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake"
          if (Test-Path $toolchain) {
            Write-Host "Toolchain file found!"
          } else {
            Write-Error "Toolchain file NOT found at $toolchain"
          }

      - name: Configure CMake
        shell: pwsh
        run: |
          $toolchain = "${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake"
          cmake -S ./src/image_sorter/cpp -B build -G "Visual Studio 17 2022" -A x64 `
            -DCMAKE_TOOLCHAIN_FILE="$toolchain" `
            -DCMAKE_LIBRARY_OUTPUT_DIRECTORY="${{ github.workspace }}\output"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: cmake-build-folder
          path: build

